
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const TipoPodcast = {
  SOLO: 'SOLO',
  ENTREVISTA: 'ENTREVISTA',
  BATE_PAPO: 'BATE_PAPO',
  INDEFINIDO: 'INDEFINIDO'
} as const

export type TipoPodcast = (typeof TipoPodcast)[keyof typeof TipoPodcast]


export const Interesse = {
  UNICO: 'UNICO',
  MENSAL: 'MENSAL'
} as const

export type Interesse = (typeof Interesse)[keyof typeof Interesse]
